/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poo.telas;

import com.poo.dao.EstoqueDAO;
import com.poo.dao.MedicamentoDAO;
import com.poo.entidades.Estoque;
import com.poo.entidades.Medicamento;
import com.poo.exceptions.CampoException;
import com.poo.exceptions.EntidadeException;
import com.poo.util.JpaUtil;
import java.text.NumberFormat;
import java.util.Arrays;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Rafael Vieira
 */
public class CadastroMedicamento extends javax.swing.JInternalFrame {

    private static CadastroMedicamento cadastroMedicamento;

    private MedicamentoDAO mdao = new MedicamentoDAO(JpaUtil.getEM());
    private EstoqueDAO edao = new EstoqueDAO(JpaUtil.getEM());
    
    private List<Medicamento> listaMedicamentos = mdao.listarMedicamentos();

    private NumberFormat formato = NumberFormat.getNumberInstance();

    

    private CadastroMedicamento() {
        initComponents();

    }

    public static CadastroMedicamento getInstance() {
        if(cadastroMedicamento == null){
            cadastroMedicamento = new CadastroMedicamento();
        }
        return cadastroMedicamento;
    }
    
    @Override
    public void dispose() {
//        limpar(Arrays.asList(descricao, fabricante, preco, quantidade));
        cadastroMedicamento = null;
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }

    private void limpar(List<JComponent> unit) {
        for (JComponent jComponent : unit) {
            if (jComponent instanceof JTextField) {
                ((JTextField) jComponent).setText(null);
            }

            if (jComponent instanceof JFormattedTextField) {
                ((JFormattedTextField) jComponent).setValue(null);
                ((JFormattedTextField) jComponent).setText(null);
            }
        }
    }

    private void continuar() {
        OUTER:
        while (true) {
            String resposta = JOptionPane.showInputDialog("Deseja continuar cadastrando? [S/N]");

            if (resposta == null) {
                JOptionPane.showMessageDialog(null, "Operação cancelada!");
                dispose();
                break;
            }

            switch (resposta) {
                case "S":
                    limpar(Arrays.asList(descricao, fabricante, preco, quantidade));
                    break OUTER;
                case "N":
                    JOptionPane.showMessageDialog(null, "Operação cancelada!");
                    dispose();
                    break OUTER;
                default:
                    JOptionPane.showMessageDialog(null, "Opção inválida! - Tente usar S ou N.");
                    
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        descricao = new javax.swing.JTextField();
        fabricante = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        formato.setMaximumFractionDigits(3);
        formato.setMinimumFractionDigits(2);
        preco = new JFormattedTextField(formato);

        formato.setMaximumIntegerDigits(3);
        formato.setMinimumIntegerDigits(2);
        quantidade = new JFormattedTextField(formato);

        jToggleButton1.setText("jToggleButton1");

        setClosable(true);
        setTitle("Cadastro de Medicamento");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("DESCRIÇÃO:");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("FABRICANTE:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("PREÇO:");

        cadastrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cadastrar.setText("CADASTRAR");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("QTD:");

        quantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(cadastrar)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(cadastrar)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
        try {
            if (descricao.getText().length() < 5) {
                descricao.setText(null);
                throw new CampoException("Verifique o campo: Descrição !");
            }

            if (preco.getValue() == null || ((Number) preco.getValue()).doubleValue() <= 0) {
                throw new CampoException("Verifique o campo: Preço !");
            }

            if (fabricante.getText().length() < 5 ) {
                fabricante.setText(null);
                throw new CampoException("Verifique o campo: Fabricante !");
            }

            if (quantidade.getValue() == null || ((Number) quantidade.getValue()).intValue() <= 0) {
                throw new CampoException("Verifique o campo: QTD !");
            }

            Medicamento medicamento = new Medicamento(descricao.getText(), fabricante.getText(),
                    ((Number) preco.getValue()).doubleValue());

            Estoque estoque = new Estoque(((Number) quantidade.getValue()).intValue(), medicamento);


            if (listaMedicamentos.isEmpty()) {
                mdao.inserirMedicamento(medicamento);
                edao.inserirEstoque(estoque);
                medicamento.setEstoque(estoque);
                mdao.atualizarMedicamento(medicamento);
                JOptionPane.showMessageDialog(null, "Medicamento Cadastrado com sucesso! ");
                continuar();
            } else {
                for (Medicamento listaMedicamento : listaMedicamentos) {
                    if (medicamento.equals(listaMedicamento)) {
                        throw new EntidadeException("Esse Medicamento já foi cadastrado!");
                    }
                }
                mdao.inserirMedicamento(medicamento);
                edao.inserirEstoque(estoque);
                medicamento.setEstoque(estoque);
                mdao.atualizarMedicamento(medicamento);
                JOptionPane.showMessageDialog(null, "Medicamento Cadastrado com sucesso! ");
                continuar();

            }

        } catch (CampoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (EntidadeException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            continuar();
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField descricao;
    private javax.swing.JTextField fabricante;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JFormattedTextField preco;
    private javax.swing.JFormattedTextField quantidade;
    // End of variables declaration//GEN-END:variables

}
