/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poo.telas;

import com.poo.dao.CompraDAO;
import com.poo.entidades.Compra;
import com.poo.tela.models.VendaTableModel;
import com.poo.util.JpaUtil;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael Vieira
 */
public class EditarCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarCompra
     */
    private static EditarCompra editarCompra;

    private EditarCompra() {
        initComponents();
    }

    @Override
    public void dispose() {
        editarCompra = null;
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }
    
    

    private CompraDAO dao = new CompraDAO(JpaUtil.getEM());

    private List<Compra> vendasNp = dao.listarComprasNpg();

    private VendaTableModel modelo = new VendaTableModel(vendasNp);

    public static synchronized EditarCompra getInstance() {
        if (editarCompra == null) {
            editarCompra = new EditarCompra();
        }

        return editarCompra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        quitar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Quitar Venda");

        tabela.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tabela.setModel(modelo);
        tabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabela);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("VENDAS A SEREM QUITADAS: ");

        quitar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        quitar.setText("QUITAR");
        quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(quitar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(quitar)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            Compra compra = modelo.getRow(tabela.getSelectedRow());

            compra.setPagamento(true);

            modelo.removeRow(tabela.getSelectedRow());
            
            JOptionPane.showMessageDialog(null, "Venda quitada com sucesso!");

            dao.atualizarCompra(compra);
        }
    }//GEN-LAST:event_quitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton quitar;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
