/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poo.telas;

import com.poo.dao.ClienteDAO;
import com.poo.dao.CompraDAO;
import com.poo.dao.EstoqueDAO;
import com.poo.dao.MedicamentoDAO;
import com.poo.util.JpaUtil;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael Vieira
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    private ClienteDAO clienteDAO = new ClienteDAO(JpaUtil.getEM());
    private CompraDAO compraDAO = new CompraDAO(JpaUtil.getEM());
    private EstoqueDAO estoqueDAO = new EstoqueDAO(JpaUtil.getEM());
    private MedicamentoDAO medicamentoDAO = new MedicamentoDAO(JpaUtil.getEM());

    public Tela() {
        initComponents();

        setIcon();

    }

    private void cadastrar(Object object) {
        OUTER:
        while (true) {
            try {
                String resposta = JOptionPane.showInputDialog(null, "Deseja cadastrar agora? [S/N]");

                switch (resposta) {
                    case "S":
                        if (object instanceof CadastroCliente) {
                            if (!CadastroCliente.getInstance().isVisible()) {
                                painelPrincipal.add(CadastroCliente.getInstance());
                                CadastroCliente.getInstance().setVisible(true);
                                break OUTER;
                            } else {
                                JOptionPane.showMessageDialog(null, "Janela já encontra-se aberta!");
                                break OUTER;
                            }
                        } else if (object instanceof CadastroMedicamento) {
                            if (!CadastroMedicamento.getInstance().isVisible()) {
                                painelPrincipal.add(CadastroMedicamento.getInstance());
                                CadastroMedicamento.getInstance().setVisible(true);
                                break OUTER;
                            } else {
                                JOptionPane.showMessageDialog(null, "Janela já encontra-se aberta!");
                                break OUTER;
                            }
                        }

                    case "N":
                        JOptionPane.showMessageDialog(null, "Operação Cancelada!");
                        break OUTER;
                    default:
                        JOptionPane.showMessageDialog(null, "Opção inválida! - Tente usar S ou N.");
                }

            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Operação Cancelada!");
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon  = new ImageIcon(getClass().getResource("fundo.jpg"));
        Image image =  icon.getImage();
        painelPrincipal = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, getWidth(),getHeight(),this);
            }

        };
        menu = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jClienteCadastro = new javax.swing.JMenuItem();
        jCadastroMedicamento = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jClienteEditar = new javax.swing.JMenuItem();
        jMedicamentoEditar = new javax.swing.JMenuItem();
        JMenuVendas = new javax.swing.JMenu();
        jCriarVenda = new javax.swing.JMenuItem();
        JquitarVendas = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jGerarRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Heisenberg's Drugstore");
        setLocation(new java.awt.Point(0, 0));
        setName("tela"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jMenuCadastro.setText("Cadastrar");
        jMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroActionPerformed(evt);
            }
        });

        jClienteCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jClienteCadastro.setText("Cadastrar Cliente");
        jClienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClienteCadastroActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jClienteCadastro);

        jCadastroMedicamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jCadastroMedicamento.setText("Cadastrar Medicamento");
        jCadastroMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroMedicamentoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jCadastroMedicamento);

        menu.add(jMenuCadastro);

        jMenuEditar.setText("Editar");

        jClienteEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jClienteEditar.setText("Editar Cliente");
        jClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClienteEditarActionPerformed(evt);
            }
        });
        jMenuEditar.add(jClienteEditar);

        jMedicamentoEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMedicamentoEditar.setText("Editar Medicamento");
        jMedicamentoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMedicamentoEditarActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMedicamentoEditar);

        menu.add(jMenuEditar);

        JMenuVendas.setText("Vendas");

        jCriarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jCriarVenda.setText("Criar Venda");
        jCriarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCriarVendaActionPerformed(evt);
            }
        });
        JMenuVendas.add(jCriarVenda);

        JquitarVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        JquitarVendas.setText("Quitar Vendas");
        JquitarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JquitarVendasActionPerformed(evt);
            }
        });
        JMenuVendas.add(JquitarVendas);

        menu.add(JMenuVendas);

        jMenuRelatorio.setText("Relatório");

        jGerarRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jGerarRelatorio.setText("Gerar Relatório Cliente");
        jGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGerarRelatorioActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jGerarRelatorio);

        menu.add(jMenuRelatorio);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jClienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClienteCadastroActionPerformed
        // TODO add your handling code here:
        if (!CadastroCliente.getInstance().isVisible()) {
            painelPrincipal.add(CadastroCliente.getInstance());
            CadastroCliente.getInstance().setVisible(true);
        }


    }//GEN-LAST:event_jClienteCadastroActionPerformed

    private void jMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCadastroActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        JpaUtil.getEM().close();
        JpaUtil.getFACTORY().close();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void jCadastroMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroMedicamentoActionPerformed
        // TODO add your handling code here:
        if (!CadastroMedicamento.getInstance().isVisible()) {
            painelPrincipal.add(CadastroMedicamento.getInstance());
            CadastroMedicamento.getInstance().setVisible(true);
        }
    }//GEN-LAST:event_jCadastroMedicamentoActionPerformed

    private void jClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClienteEditarActionPerformed
        // TODO add your handling code here:
        if (clienteDAO.listarClientes().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum cliente foi cadastrado!");
            cadastrar(CadastroCliente.getInstance());
        } else {
            if (!EditarCliente.getInstance().isVisible()) {
                painelPrincipal.add(EditarCliente.getInstance());
                EditarCliente.getInstance().setVisible(true);
            }
        }

    }//GEN-LAST:event_jClienteEditarActionPerformed

    private void jMedicamentoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMedicamentoEditarActionPerformed
        // TODO add your handling code here:
        if (medicamentoDAO.listarMedicamentos().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum medicamento foi cadastrado!");
            cadastrar(CadastroMedicamento.getInstance());
        } else {
            if (!EditarMedicamento.getInstance().isVisible()) {
                painelPrincipal.add(EditarMedicamento.getInstance());
                EditarMedicamento.getInstance().setVisible(true);
            }
        }
    }//GEN-LAST:event_jMedicamentoEditarActionPerformed

    private void jCriarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCriarVendaActionPerformed
        // TODO add your handling code here:
         if (clienteDAO.listarClientes().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum cliente foi cadastrado!");
            cadastrar(CadastroCliente.getInstance());
        }else if(medicamentoDAO.listarMedicamentos().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum medicamento foi cadastrado!");
            cadastrar(CadastroMedicamento.getInstance());
        }else{
            if (!CadastroCompra.getInstance().isVisible()) {
                painelPrincipal.add(CadastroCompra.getInstance());
                CadastroCompra.getInstance().setVisible(true);
            }
        }
    }//GEN-LAST:event_jCriarVendaActionPerformed

    private void JquitarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JquitarVendasActionPerformed
        // TODO add your handling code here:
        if(compraDAO.listarComprasNpg().isEmpty()){
          JOptionPane.showMessageDialog(null, "Nenhuma venda a quitar!");  
        }else{
            
            if (!EditarCompra.getInstance().isVisible()) {
                painelPrincipal.add(EditarCompra.getInstance());
                EditarCompra.getInstance().setVisible(true);
            }
        }
    }//GEN-LAST:event_JquitarVendasActionPerformed

    private void jGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGerarRelatorioActionPerformed
        // TODO add your handling code here:
        if(compraDAO.listarCompras().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhuma venda cadastrada!");  
        }else{
            if (!RelatorioCliente.getInstance().isVisible()) {
                painelPrincipal.add(RelatorioCliente.getInstance());
                RelatorioCliente.getInstance().setVisible(true);
            }
        }
    }//GEN-LAST:event_jGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuVendas;
    private javax.swing.JMenuItem JquitarVendas;
    private javax.swing.JMenuItem jCadastroMedicamento;
    private javax.swing.JMenuItem jClienteCadastro;
    private javax.swing.JMenuItem jClienteEditar;
    private javax.swing.JMenuItem jCriarVenda;
    private javax.swing.JMenuItem jGerarRelatorio;
    private javax.swing.JMenuItem jMedicamentoEditar;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenuBar menu;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
